//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationMVC3.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class pelicula
    {
        public int idPelicula { get; set; }
        public string titulo { get; set; }
        public Nullable<int> duracion { get; set; }
        public string publicacion { get; set; }
    }
}
